### PR TITLE
[F3D] Pass in shade alpha into fog blender instead of disabling it when fog is off

### PR DESCRIPTION
**Pull request by Lilaa3**
Fixes preview of fogshade with no fog geo mode enabled
image
image

### CODE REVIEW

**Comment by Lilaa3** [comment]
To show the change a bit better, here are 4 materials, one with fog and a fog blender, fog with no fog in the blender, no fog but fog in the blender and neither
Main:
image
PR:
image
[Here is the test file, it's in 3.2, upgrade materials in main or in this pr to see how they differ in behavior](https://github.com/user-attachments/files/16473205/Fog.Blender.Test.blend.zip)

**Review by Reonu — APPROVED** [review]
I tested it and seems to work well, fixes the issue I had on my blend, lila's blend also works as expected

**Comment by jesusyoshi54** [comment]
image
if you swap global fog it doesn't update the links properly

**Comment by Lilaa3** [comment]
@jesusyoshi54 Issue has been fixed, also added two comments

**Review by jesusyoshi54 — APPROVED** [review]
Works well and code looks nice :)

**Pull request merged**
