### PR TITLE
[SM64] - Fix animation translation

### PR DESCRIPTION
**Pull request by Lilaa3**
I tested this method in my own branches, it works and it fixes translation issues (see https://discord.com/channels/874816709855440926/1196963740705357894), along with being faster

### CODE REVIEW

**Comment by Lilaa3** [comment]
I know for a fact this works please let me merge

**Comment by Lilaa3** [comment]
https://discord.com/channels/874816709855440926/874818719220633672/1197010611788333117 was also caused by the old logic, animation exports properly with this pr

**Comment by Lilaa3** [comment]
Just had confirmation of another person having issues fixed from this, I'm waiting on kaze to confirm this fixes his animations too!

**Review by jesusyoshi54 — APPROVED** [review]
You are superstar. Now please make mario animation exporting work with one click

**Comment by Lilaa3** [comment]
Working on it miss 🫡

**Pull request merged**
