### PR TITLE
Some f3d parser cleanup

### PR DESCRIPTION
**Pull request by Dragorn421**
I did not break importing OoT scenes so it must be fine 4Head

### CODE REVIEW

**Review by Yanis42 — COMMENTED** [review]
idk much about f3d but code looks ok to me (I haven't tried this yet)

**Comment by jesusyoshi54** [comment]
While testing this I found out that sm64 straight up does not work with the f3d importer. I am not surprised at all.

I then tested the f3d importer with some Kirby display lists that I exported and it worked just fine. So therefore I approve :)

**Review by jesusyoshi54 — APPROVED** [review]
It seems like sm64 didn't work before, or after this. That will be something to address in a different PR which is probably a long time coming for the f3d importer.

**Comment by Dragorn421** [comment]
Thanks
I'd like to wait for #271 to be in before merging this in case it conflicts

**Comment by Dragorn421** [comment]
merged main and #271, seems to be fine still :) will merge soon tm

**Pull request merged**
