### PR TITLE
Write OoT scene lighting data as hex

### PR DESCRIPTION
**Pull request by sauraen**
Match decomp tools formatting

### CODE REVIEW

**Review by Dragorn421 — COMMENTED** [review]
This includes changes from #3 so we'll get the other PR merged first (or you can edit your branch, as you want), but otherwise this looks good.

**Comment by sauraen** [comment]
I needed to match the lighting settings of a vanilla scene, so I needed to compare the values without putting every one through a hex converter. If someone wants to make a PR to change the decomp toolchain instead, and reject this PR, that's fine with me.

**Comment by Zelllll** [comment]
I'm fine with merging this for now but eventually it needs fixed decomp side, however they decided to ban me so RIP

**Comment by fig02** [comment]
I would just wait personally and we'll change whatever is needed decomp side.
Whats the issue exactly? Lighting stuff in light settings from rooms? So a zapd change?

**Comment by Zelllll** [comment]
Another issue is that the struct is totally wrong, and I fixed it in MM already actually I think, and you also have it fixed in your Kankyo branch except you made a duplicate struct. Anyways a bunch of struct members are erroneously swapped for some reason.

**Comment by Zelllll** [comment]
And also the lighting rgb should be in decimal rather than hex since we always do colors that way, that was the main issue here

**Comment by fig02** [comment]
if its dependent on kankyo stuff, then this hotfix seems appropriate

**Comment by Zelllll** [comment]
Alright this should be good then but I believe Dragorn said that this pr also includes other unrelated changes that need reverted, right?

**Comment by Dragorn421** [comment]
Yeah, this includes changes from #3
either revert the changes in a new commit, or:
`git checkout LightingWriteHex`
`git reset --soft main` (resets the branch history to main but doesn't affect working directory)
`git reset -p` and reset index changes related to #3
`git commit`
`git push --force` (overwrite the current history)

**Comment by sauraen** [comment]
I've rebased the branch as you requested. I'm sorry for the trouble, these branches are from the bitbucket era where merges did not happen often. I needed to not have to switch back and forth between branches to actually use the plugin.

**Review by Dragorn421 — APPROVED** [review]

**Pull request merged**
