### PR TITLE
Added Homebrew Game Mode 

### PR DESCRIPTION
**Pull request by jesusyoshi54**
Game specific panels are hidden and `homebrew_compatible` type options are used while in that game mode.

### CODE REVIEW

**Comment by jesusyoshi54** [comment]
Issue #342 should be solved with this PR

**Comment by Lilaa3** [comment]
Can I convince you to add some quick and dirty update logic for this during upgrade_changed_props
```python
for scene in bpy.data.scenes:
        if scene.get("decomp_compatible", False):
            scene.gameEditorMode = "Homebrew"
            del scene["decomp_compatible"]
```

**Review by Lilaa3 — APPROVED** [review]
Looks good to me, operators work correctly, upgrade code is implemented as requested

**Comment by Lilaa3** [comment]
I wonder if there is a good way to standardize upgrade logic

**Comment by jesusyoshi54** [comment]
Maybe for a cleanup PR. It definitely could be something thrown into utilities

**Pull request merged**
