### PR TITLE
[SM64] Update included mario models to v6

### PR DESCRIPTION
**Pull request by Lilaa3**
Replace lowpolyskinnedmario by its v5 variant (upgraded to v6), there shouldn´t be two.
I think it's also worth considering removing the low poly blend in place of yoshi milkman's skinned mario, or remove the mario models all together to be safe (would ideally be done post c geolayout importing).

### CODE REVIEW

**Comment by Dragorn421** [comment]
How about we remove all the blends and create a new repo for them

**Comment by Lilaa3** [comment]
> How about we remove all the blends and create a new repo for them

Repo where exactly? I think this just has to be removed all together once importing is really easy

**Comment by Dragorn421** [comment]
Fast-64/fast64-models, and yeah we can remove them from there later. It'll still be in the git history of course but oh well so is it here

**Comment by Lilaa3** [comment]
> Fast-64/fast64-models, and yeah we can remove them from there later. It'll still be in the git history of course but oh well so is it here

If you aren´t busy you could create that and I'll pr (I think I can do it too now?), but it's still not safe aha

**Pull request closed without merging**
