### PR TITLE
Bump version to v2.2.0

### PR DESCRIPTION
**Pull request by Dragorn421**
Can also use this PR to discuss the release (e.g. if we should wait for anything)

Yanies mentioned it may be good to wait for f3dex3 preview, but since that's not anywhere near ready afaik I think it's fine to have a release in between

It's been 2 years since the previous release :sweat_smile: 

If you have permission (I'm not sure who does) there is a release draft for 2.2.0 on the releases page https://github.com/Fast-64/fast64/releases (not visible by everyone apparently)

### CODE REVIEW

**Review by Lilaa3 — DISMISSED** [review]
Sauren said the f3dex3 preview stuff is gonna take awhile.

**Comment by Lilaa3** [comment]
Change-log looks perfect too!

**Comment by ariahiro64** [comment]
there is a major bug with map importer for oot that applies the scene function to every single material causing almost guaranteed crashes. it is NOT ready for a release in this state.

**Comment by ariahiro64** [comment]
#252 the work around is there for the issue so i guess you guys now know where to point people with issues

**Comment by Dragorn421** [comment]
> there is a major bug with map importer for oot that applies the scene function to every single material causing almost guaranteed crashes. it is NOT ready for a release in this state.

Overlooking this because
- it is not a major bug (exporting imported stuff is inherently fragile, and also not the primary goal of fast64)
- though it's a pain you can fix the materials manually
- afaik this isn't a regression, the issue has existed since scene importing was implemented
- the 2.1.0 release already had scene importing (so, including the issue)

I am not trying to start an argument at all, just explaining why releasing despite this comment.

**Comment by ariahiro64** [comment]
> > there is a major bug with map importer for oot that applies the scene function to every single material causing almost guaranteed crashes. it is NOT ready for a release in this state.
> 
> Overlooking this because
> 
>     * it is not a major bug (exporting imported stuff is inherently fragile, and also not the primary goal of fast64)
> 
>     * though it's a pain you can fix the materials manually
> 
>     * afaik this isn't a regression, the issue has existed since scene importing was implemented
> 
>     * the 2.1.0 release already had scene importing (so, including the issue)
> 
> 
> I am not trying to start an argument at all, just explaining why releasing despite this comment.

To add on we've also discussed it on the discord server and we feel just making people aware of the workaround is enough

**Review by ariahiro64 — APPROVED** [review]

**Review by Yanis42 — COMMENTED** [review]
since we have an actual fix I'd like to see #275 merged before releasing 2.2.0, otherwise I don't have any objections

**Comment by Dragorn421** [comment]
> since we have an actual fix I'd like to see #275 merged before releasing 2.2.0, otherwise I don't have any objections

I think it will take a bit more time to find a proper fix, so in agreement with Yanies we're going to release as is

**Pull request merged**
